pragma Singleton
import QtQuick
import org.argvus.i18n 1.0

QtObject {
    function tr(key, args) { return I18n.tr("control-panel", key, args) }

    readonly property string cardTitleUser:          tr("card.user.title")
    readonly property string cardTitleNotifications: tr("card.notifications.title")
    readonly property string cardTitleCalendar:      tr("card.calendar.title")
    readonly property string cardTitleWeather:       tr("card.weather.title")
    readonly property string cardTitleVolume:        tr("card.volume.title")
    readonly property string cardTitleBrightness:    tr("card.brightness.title")
    readonly property string cardTitleNetwork:       tr("card.network.title")
    readonly property string cardTitleBluetooth:     tr("card.bluetooth.title")
    readonly property string cardTitleSystem:        tr("card.system.title")
    readonly property string cardTitleAppearance:    tr("card.appearance.title")
    readonly property string cardTitleSession:       tr("card.session.title")
    readonly property string cardTitleSpacesBordersPosition: tr("card.spaces_borders_position.title")
    readonly property string cardTitlePower:         tr("card.power.title")
    readonly property string cardTitleDisplay:       tr("card.display.title")
    readonly property string cardTitleAbout:         tr("card.about.title")
    readonly property string loadingCards:            tr("loading.cards")

    readonly property string aboutHint: tr("about.hint")
    readonly property string aboutOpen: tr("about.open")

    readonly property string displayScale:      tr("display.scale")
    readonly property string displayDpi:        tr("display.dpi")
    readonly property string displayBrightness: tr("display.brightness")
    readonly property string displayPowerOn:    tr("display.power_on")
    readonly property string displayPowerOff:   tr("display.power_off")
    readonly property string displayOpenCenter: tr("display.open_center")

    readonly property string spacesOuterGapTop:    tr("spaces.taskbar_outer_gap_top")
    readonly property string spacesOuterGapLeft:   tr("spaces.taskbar_outer_gap_left")
    readonly property string spacesOuterGapRight:  tr("spaces.taskbar_outer_gap_right")
    readonly property string spacesOuterGapBottom: tr("spaces.taskbar_outer_gap_bottom")
    readonly property string spacesGapIn:         tr("spaces.gap_in")
    readonly property string spacesGapOutTop:     tr("spaces.gap_out_top")
    readonly property string spacesGapOutLeft:    tr("spaces.gap_out_left")
    readonly property string spacesGapOutRight:   tr("spaces.gap_out_right")
    readonly property string spacesGapOutBottom:  tr("spaces.gap_out_bottom")
    readonly property string spacesRounded:       tr("spaces.rounded")
    readonly property string spacesRounding:      tr("spaces.rounding")
    readonly property string spacesEdgeThickness: tr("spaces.edge_thickness")
    readonly property string spacesThickness:     tr("spaces.thickness")
    readonly property string btnApply:            tr("action.apply")

    readonly property string taskbarPositionLabel: tr("spaces.taskbar_position")
    readonly property string taskbarSpacesTitle:   tr("spaces.taskbar_spaces")
    readonly property string windowSpacesTitle:    tr("spaces.window_spaces")
    readonly property string generalBordersTitle:  tr("spaces.general_borders")
    readonly property string taskbarTop:           tr("taskbar.top")
    readonly property string taskbarBottom:        tr("taskbar.bottom")

    readonly property string notifNone:        tr("notifications.none")
    readonly property string notifClear:       tr("notifications.clear")
    readonly property string notifAppUnknown:  tr("notifications.app_unknown")
    readonly property string notifDnd:          tr("notifications.do_not_disturb")
    readonly property string notifDndOn:        tr("notifications.dnd_enabled")
    readonly property string notifDndOff:       tr("notifications.dnd_disabled")
    readonly property string notifUnavailable:  tr("notifications.unavailable")
    readonly property string notifReadFailed:   tr("notifications.read_failed")
    readonly property string notifChangeFailed: tr("notifications.change_failed")

    readonly property string netTitle:        tr("network.title")
    readonly property string netDisabled:     tr("network.disabled")
    readonly property string netConnected:    tr("network.connected")
    readonly property string netLimited:      tr("network.limited")
    readonly property string netNoConnection: tr("network.no_connection")

    readonly property string btTitle:           tr("bluetooth.title")
    readonly property string btEnabled:         tr("bluetooth.enabled")
    readonly property string btDisabled:        tr("bluetooth.disabled")
    readonly property string btConnected:       tr("bluetooth.connected")
    readonly property string btNoController:    tr("bluetooth.no_controller")
    readonly property string btUnavailable:     tr("bluetooth.unavailable")
    readonly property string btOpenManager:     tr("bluetooth.open_manager")
    readonly property string btManagerOptional: tr("bluetooth.manager_optional")
    readonly property string btController:      tr("bluetooth.controller")

    readonly property string weatherLoading:   tr("weather.loading")
    readonly property string weatherError:     tr("weather.error")
    readonly property string weatherFeelsLike: tr("weather.feels_like")
    readonly property string weatherHumidity:  tr("weather.humidity")
    readonly property string weatherWind:      tr("weather.wind")
    readonly property string weatherConfigure: tr("weather.configure")
    readonly property string weatherRefresh:   tr("weather.refresh")
    readonly property string volumeMuted:       tr("volume.muted")

    readonly property string btnWallpaper:            tr("appearance.wallpaper")
    readonly property string btnTheme:                tr("appearance.theme")
    readonly property string btnAccent:               tr("appearance.accent")
    readonly property string hexColor:                tr("appearance.hex_color")
    readonly property string applyAccent:             tr("appearance.apply_accent")
    readonly property string resetAccent:             tr("appearance.reset_accent")
    readonly property string widgetTelemetryTitle:    tr("appearance.widget.title")
    readonly property string widgetTelemetryEnabled:  tr("appearance.widget.enabled")
    readonly property string widgetTelemetryDisabled: tr("appearance.widget.disabled")
    readonly property string animationsTitle:         tr("appearance.animations.title")
    readonly property string animationsEnabled:       tr("appearance.animations.enabled")
    readonly property string animationsDisabled:      tr("appearance.animations.disabled")
    readonly property string transparencyTitle:       tr("appearance.transparency.title")
    readonly property string transparencyEnabled:     tr("appearance.transparency.enabled")
    readonly property string transparencyDisabled:    tr("appearance.transparency.disabled")
    readonly property string idleLockTitle:           tr("appearance.lock.title")
    readonly property string idleLockNever:           tr("appearance.lock.never")
    readonly property string lockDpmsTitle:           tr("appearance.dpms.title")
    readonly property string lockDpmsEnabled:         tr("appearance.dpms.enabled")
    readonly property string lockDpmsDisabled:        tr("appearance.dpms.disabled")
    readonly property string keepAwakeTitle:           tr("session.keep_awake.title")
    readonly property string keepAwakeEnabled:         tr("session.keep_awake.enabled")
    readonly property string keepAwakeDisabled:        tr("session.keep_awake.disabled")

    readonly property string userTabAvatar:        tr("user.tab.avatar")
    readonly property string userTabName:          tr("user.tab.name")
    readonly property string userTabPassword:      tr("user.tab.password")
    readonly property string userAvatarActive:     tr("user.avatar.set")
    readonly property string userAvatarNone:       tr("user.avatar.none")
    readonly property string userAvatarChange:     tr("user.avatar.change")
    readonly property string userAvatarRemove:     tr("user.avatar.remove")
    readonly property string userAvatarOk:         tr("user.avatar.updated")
    readonly property string userAvatarRemoved:    tr("user.avatar.removed")
    readonly property string userAvatarError:      tr("user.avatar.error")
    readonly property string user_name_label:      tr("user.name.label")
    readonly property string user_name_hint:       tr("user.name.hint")
    readonly property string user_name_save:       tr("user.name.save")
    readonly property string user_name_ok:         tr("user.name.updated")
    readonly property string user_name_error:      tr("user.name.error")
    readonly property string userPasswordDesc:     tr("user.password.description")
    readonly property string userPasswordCurrent:  tr("user.password.current")
    readonly property string userPasswordNew:      tr("user.password.new")
    readonly property string userPasswordConfirm:  tr("user.password.confirm")
    readonly property string userPasswordMismatch: tr("user.password.mismatch")
    readonly property string userPasswordChange:   tr("user.password.change")
    readonly property string userPasswordOk:       tr("user.password.changed")
    readonly property string userPasswordError:    tr("user.password.error")
    readonly property string userPasswordHint:     tr("user.password.hint")

    readonly property var profiles: [
        { id: "power-saver", label: tr("power.profile.power_saver"), icon: "󰾆", desc: tr("power.profile.power_saver.description") },
        { id: "balanced", label: tr("power.profile.balanced"), icon: "󰾅", desc: tr("power.profile.balanced.description") },
        { id: "performance", label: tr("power.profile.performance"), icon: "󰓅", desc: tr("power.profile.performance.description") }
    ]
    readonly property string powerSaverActive:     tr("power.active.power_saver")
    readonly property string powerPerfActive:      tr("power.active.performance")
    readonly property string powerBalancedActive:  tr("power.active.balanced")

    readonly property var monthNames: [
        tr("calendar.month.1"), tr("calendar.month.2"), tr("calendar.month.3"),
        tr("calendar.month.4"), tr("calendar.month.5"), tr("calendar.month.6"),
        tr("calendar.month.7"), tr("calendar.month.8"), tr("calendar.month.9"),
        tr("calendar.month.10"), tr("calendar.month.11"), tr("calendar.month.12")
    ]
    readonly property var dayNames: [
        tr("calendar.day.1"), tr("calendar.day.2"), tr("calendar.day.3"),
        tr("calendar.day.4"), tr("calendar.day.5"), tr("calendar.day.6"),
        tr("calendar.day.7")
    ]
    readonly property string stateOn:                 tr("state.on")
    readonly property string stateOff:                tr("state.off")
    readonly property string weatherLocationAuto:     tr("weather.location.auto")
    readonly property string weatherLocationTitle:    tr("weather.location.title")
    readonly property string weatherLocationPrompt:   tr("weather.location.prompt")
    readonly property string weatherLocationTooLong:  tr("weather.location.too_long")
    readonly property string weatherNotificationTitle: tr("weather.notification.title")
    readonly property string weatherNotificationAuto:  tr("weather.notification.auto")
    readonly property string weatherConditionClearSky:   tr("weather.condition.clear_sky")
    readonly property string weatherConditionPartlyCloudy: tr("weather.condition.partly_cloudy")
    readonly property string weatherConditionFog:        tr("weather.condition.fog")
    readonly property string weatherConditionDrizzle:    tr("weather.condition.drizzle")
    readonly property string weatherConditionRain:       tr("weather.condition.rain")
    readonly property string weatherConditionSnow:       tr("weather.condition.snow")
    readonly property string weatherConditionRainShowers: tr("weather.condition.rain_showers")
    readonly property string weatherConditionSnowShowers: tr("weather.condition.snow_showers")
    readonly property string weatherConditionThunderstorm: tr("weather.condition.thunderstorm")
    readonly property string weatherConditionUnknown:   tr("weather.condition.unknown")
}
